version: "3.8"

services:
  app:
    build: .
    container_name: leffakerho-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/leffakerho
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - leffakerho-net

  db:
    image: postgres:15
    container_name: leffakerho-db
    environment:
      POSTGRES_DB: leffakerho
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - leffakerho-net

volumes:
  pgdata:

networks:
  leffakerho-net:
